### PR TITLE
Jenkins trigger for pylint branches

### PR DESCRIPTION
**Pull request by Christian-B**
tests:
These all share the same branch name so are tested together but can be merged independent

https://github.com/SpiNNakerManchester/SpiNNUtils/pull/192
https://github.com/SpiNNakerManchester/SpiNNMachine/pull/186
https://github.com/SpiNNakerManchester/SpiNNMan/pull/302
https://github.com/SpiNNakerManchester/DataSpecification/pull/123
https://github.com/SpiNNakerManchester/PACMAN/pull/466
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1012
https://github.com/SpiNNakerManchester/sPyNNaker/pull/1267
https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/93
https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/228
https://github.com/SpiNNakerManchester/TestBase/pull/23
https://github.com/SpiNNakerManchester/IntroLab/pull/35
https://github.com/SpiNNakerManchester/PyNN8Examples/pull/90
https://github.com/SpiNNakerManchester/SpiNNGym/pull/61
https://github.com/SpiNNakerManchester/sPyNNakerVisualisers/pull/25
https://github.com/SpiNNakerManchester/MarkovChainMonteCarlo/pull/40
https://github.com/SpiNNakerManchester/spalloc_server/pull/77
https://github.com/SpiNNakerManchester/spalloc/pull/70

### CODE REVIEW

**Comment by Christian-B** [comment]
Do not close as will be used for more branches.

**Comment by dkfellows** [comment]
This all done now?

**Comment by Christian-B** [comment]
> This all done now?

No.
Spynakker is help due to a discussion on https://github.com/SpiNNakerManchester/sPyNNaker/pull/1181

There is a second of prs coming

 This will probably be an long term project as new pylint warnings slip in and need fix.

**Comment by rowleya** [comment]
I think this can be closed now... but leaving in case I am wrong...

**Comment by Christian-B** [comment]
all merged

**Pull request closed without merging**
